package edu.neu.csye6200.students.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.neu.csye6200.classes.Classroom;
import edu.neu.csye6200.classes.School;
import edu.neu.csye6200.classes.Teacher;
import utility.EmailValidator;
import utility.mapStringNumber;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddTeacherView {
    private JPanel mainPanel;
    private JTextField idField;
    private JTextField salaryField;
    private JTextField emailField;
    private JTextField nameField;
    private JLabel salaryLabel;
    private JLabel nameLabel;
    private JLabel idlabel;
    private JLabel emailLabel;
    private JButton submitButton;
    private JTextField ageField;
    private JLabel ageLabel;

    public AddTeacherView(DataView view) {
        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String name = nameField.getText();
                int salary = Integer.parseInt(salaryField.getText());
                String email = emailField.getText();
                int id = Integer.parseInt(idField.getText());
                int age = Integer.parseInt(ageField.getText());

                EmailValidator emailValidator = new EmailValidator();

                if (!emailValidator.validate(emailField.getText().trim())) {
                    System.out.print("Invalid Email ID");
                    JOptionPane.showMessageDialog(null, "your Email seems weird...");
                } else {
                    // There must be a better solution
//                    Classroom newClassroom = new Classroom();
//                    School.classrooms.add(newClassroom);
                    School.addTeacher(new Teacher(id, name, email, age, salary));
                    String comboSequence = mapStringNumber.generateNextPermutation(School.classrooms.size());
                    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
                    comboBoxModel.addElement(" ");
                    for (Classroom cl : School.classrooms) {
                        comboBoxModel.addElement(cl);
                    }
                    view.classroomCombox.setModel(comboBoxModel);
                }


            }
        });
    }
    public AddTeacherView(TeacherDetails teacherDetails) {
        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String name = nameField.getText();
                int salary = Integer.parseInt(salaryField.getText());
                String email = emailField.getText();
                int id = Integer.parseInt(idField.getText());
                int age = Integer.parseInt(ageField.getText());

                EmailValidator emailValidator = new EmailValidator();

                if (!emailValidator.validate(emailField.getText().trim())) {
                    System.out.print("Invalid Email ID");
                    JOptionPane.showMessageDialog(null, "your Email seems weird...");
                } else {
                    // There must be a better solution
//                    Classroom newClassroom = new Classroom();
//                    School.classrooms.add(newClassroom);
                    School.addTeacher(new Teacher(id, email, name, age, salary));
                    teacherDetails.maintableModel.addRow(new Object[]{id, name, email, age, salary});
//                    String comboSequence = mapStringNumber.generateNextPermutation(School.classrooms.size());
//                    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
////                    comboBoxModel.addElement(" ");
//                    for (Classroom cl : School.classrooms) {
//                        comboBoxModel.addElement(cl);
//                    }
//                    view.classroomCombox.setModel(comboBoxModel);
                }


            }
        });
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(7, 2, new Insets(0, 0, 0, 0), -1, -1));
        idField = new JTextField();
        mainPanel.add(idField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        salaryField = new JTextField();
        mainPanel.add(salaryField, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        emailField = new JTextField();
        mainPanel.add(emailField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        nameField = new JTextField();
        mainPanel.add(nameField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        idlabel = new JLabel();
        idlabel.setHorizontalTextPosition(11);
        idlabel.setText("ID:");
        mainPanel.add(idlabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameLabel = new JLabel();
        nameLabel.setHorizontalTextPosition(11);
        nameLabel.setText("Name: ");
        mainPanel.add(nameLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        emailLabel = new JLabel();
        emailLabel.setHorizontalTextPosition(11);
        emailLabel.setText("Email:");
        mainPanel.add(emailLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        salaryLabel = new JLabel();
        salaryLabel.setHorizontalTextPosition(11);
        salaryLabel.setText("Salary:");
        mainPanel.add(salaryLabel, new GridConstraints(4, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        submitButton = new JButton();
        submitButton.setText("Submit");
        mainPanel.add(submitButton, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ageLabel = new JLabel();
        ageLabel.setText("Age");
        mainPanel.add(ageLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ageField = new JTextField();
        mainPanel.add(ageField, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
