package edu.neu.csye6200.students.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import database.Table;
import database.TableModel;
import database.TableProperty;
import edu.neu.csye6200.classes.Classroom;
import edu.neu.csye6200.classes.School;
import edu.neu.csye6200.classes.Teacher;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;

public class ClassroomDetails {
    private JTable classroomTable;
    private JPanel jPanel1;
    private JFrame frame = new JFrame();
    DefaultTableModel maintableModel = new DefaultTableModel();
    String[] columnNames = {"Id", "ClassroomName", "Teacher"};

    public ClassroomDetails() {
        System.out.println("------------------");
        School.classrooms.add(new Classroom("Calss", new Teacher(1, "jka", "ks@gmail.com", 23, 323)));
        Object[][] classRoomObject = new Object[School.classrooms.size()][3];
        int i = 0;
        for (Classroom c : School.classrooms) {
            classRoomObject[i][0] = i + 1;
            classRoomObject[i][1] = c.getName();
            classRoomObject[i][2] = c.getTeacher().toString();
        }
//        classroomTable = new Table();
        maintableModel.setDataVector(classRoomObject, columnNames);
        classroomTable.setModel(maintableModel);
        classroomTable.setBounds(30, 40, 200, 300);

        // adding it to JScrollPane
        JScrollPane sp = new JScrollPane(classroomTable);
        frame.add(sp);
        // Frame Size
        frame.setSize(500, 200);
        // Frame Visible = true
        frame.setVisible(true);
//        classroomTable.render();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel1 = new JPanel();
        jPanel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        classroomTable = new JTable();
        jPanel1.add(classroomTable, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer1 = new Spacer();
        jPanel1.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel1;
    }

}
