package edu.neu.csye6200.students.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Dashboard extends JFrame {
    private JPanel jPanel1;
    private JLabel headingLabel;
    private JButton studentsButton;
    private JButton teachersButton;
    private JButton classroomsButton;

    public Dashboard() {
        classroomsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
////                JFrame jFrame = new JFrame("ClassRoom Details");
//                setContentPane(new ClassroomDetails().$$$getRootComponent$$$());
//                pack();
//                setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
                new ClassroomDetails();
            }
        });
        teachersButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                JFrame jFrame = new JFrame("Teacher Details");
//                setContentPane(new ClassroomDetails().$$$getRootComponent$$$());
//                pack();
//                setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
                new TeacherDetails();
            }
        });
        studentsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new DataView();
            }
        });
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setContentPane(this.$$$getRootComponent$$$());
        this.pack();
        setVisible(true);
        setResizable(true); // make it nonchangeable
        setDefaultCloseOperation(EXIT_ON_CLOSE); // exit when closing
        Dimension curScreenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((curScreenSize.width - 600) / 2, (curScreenSize.height - 400) / 2);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel1 = new JPanel();
        jPanel1.setLayout(new GridLayoutManager(7, 2, new Insets(32, 32, 32, 32), -1, -1, true, false));
        jPanel1.setMinimumSize(new Dimension(1000, 174));
        jPanel1.setPreferredSize(new Dimension(1000, 400));
        headingLabel = new JLabel();
        headingLabel.setText("Student Management System");
        jPanel1.add(headingLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        studentsButton = new JButton();
        studentsButton.setMargin(new Insets(24, 24, 24, 24));
        studentsButton.setText("Students");
        jPanel1.add(studentsButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        classroomsButton = new JButton();
        classroomsButton.setMargin(new Insets(24, 24, 24, 24));
        classroomsButton.setText("Classrooms");
        jPanel1.add(classroomsButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        teachersButton = new JButton();
        teachersButton.setMargin(new Insets(24, 24, 24, 24));
        teachersButton.setText("Teachers");
        jPanel1.add(teachersButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel1;
    }

}
